# Generated by Django 5.2 on 2025-04-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gains_be', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
